services:
  authentication-api:
    build: .
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .:/app
    depends_on:
      - authentication-database
    networks:
      - muimi_container_network

  authentication-database:
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - muimi_container_network

networks:
  muimi_container_network:
    external: true